repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-mod-tidy
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.17.0
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
